"""initial_schema

Revision ID: de6665ec4e05
Revises: 8c11ffb803e5
Create Date: 2026-07-30 16:20:40.072297
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'de6665ec4e05'
down_revision: Union[str, None] = '8c11ffb803e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
